title: Line of Sight Analyst
author: Jan Caha
email: jan.caha@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Line of Sight Analyst toolbox is a Python toolbox for ArcGIS of version 10.x. 
  The tool aims to extend possibilities provided by existing tools Construct Sight Lines 
  and Line of Sight in ArcGIS 3D Analyst's Visibility toolbox.
baseurl: "/Line-of-Sight-Analyst" # the subpath of your site, e.g. /blog
url: "https://jancaha.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

destination: ../docs/

github_link: https://github.com/JanCaha/Line-of-Sight-Analyst
github_issue: https://github.com/JanCaha/Line-of-Sight-Analyst/issues
github_relases: https://github.com/JanCaha/Line-of-Sight-Analyst/releases

version: 0.7.0
release_year: 2018
licence: GPLv3
licence_ling: https://www.gnu.org/licenses/gpl-3.0.en.html


collections:
  tools:
    output: true
    permalink: /:collection/:name/

# Build settings
markdown: kramdown
highlighter: rouge

plugins_dir: _plugins


exclude:
  - Gemfile
  - Gemfile.lock
